# This is a basic workflow to help you get started with Actions

name: Build and Test Electrostatic-Sandbox Framework

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
#    build-electrostatic:
#      # runner images with architectures (variants)
#      runs-on: ${{ matrix.os }}
#      strategy:
#        matrix:
#          os: [ 'ubuntu-latest' ]
#      name: Build Electrostatic
#
#      # Steps represent a sequence of tasks that will be executed as part of the job
#      steps:
#        - name: Checkout Job
#          uses: actions/checkout@v3
#
#        - name: Setup Electrostatic-Sandbox Workstation
#          run: chmod +rwx ./helper-scripts/setup-environment/setup-sandbox.sh && ./helper-scripts/setup-environment/setup-sandbox.sh
#
#        - name: User's Permissions Granting
#          run: chmod +rwx ./helper-scripts/project-impl/*.sh && chmod +rwx ./helper-scripts/ci-cd/*.sh
#
#        - name: Compiling electrostatic-core Native Binaries
#          run: ./helper-scripts/ci-cd/compile-electrostatic.sh ""
#
#        - name: Testing electrostatic-core Native Binaries
#          run: ./helper-scripts/ci-cd/test-electrostatic.sh "hello_comm.c"
#
#        - name: Compiling electrostatic4j Java Binding API
#          run: ./helper-scripts/ci-cd/compile-e4j.sh
#
#        - name: Testing electrostatic4j Java Binding API
#          run: ./helper-scripts/ci-cd/test-e4j.sh
#
#        - name: Building electrostatic4j:serial4j
#          run: ./helper-scripts/ci-cd/compile-serial4j.sh

    build-electrostatic-primer:
      # runner images with architectures (variants)
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ 'ubuntu-latest' ]
      name: Build Electrostatic Primer

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - name: Checkout Job
          uses: actions/checkout@v3

        - name: Setup Electrostatic-Sandbox Workstation
          run: chmod +rwx ./helper-scripts/setup-environment/setup-sandbox.sh && ./helper-scripts/setup-environment/setup-sandbox.sh

        - name: User's Permissions Granting
          run: chmod +rwx ./helper-scripts/project-impl/*.sh && chmod +rwx ./helper-scripts/ci-cd/*.sh
        
        - name: Compiling electrostatic-core Native Binaries
          run: ./helper-scripts/ci-cd/compile-electrostatic.sh "-primer"

        - name: Testing electrostatic-core Native Binaries
          run: ./helper-scripts/ci-cd/test-electrostatic.sh "hello_comm.c"

        - name: Testing "hello_vector2d.c"
          run: ./helper-scripts/ci-cd/test-electrostatic.sh "hello_vector2d.c"

        - name: Testing "hello_contiguous_buffer.c"
          run: ./helper-scripts/ci-cd/test-electrostatic.sh "hello_lists.c"

        - name: Testing "hello_unittest.c"
          run: ./helper-scripts/ci-cd/test-electrostatic.sh "hello_unittest.c"

        - name: Testing "hello_switching_mux.c"
          run: ./helper-scripts/ci-cd/test-electrostatic.sh "hello_switching_mux.c"

        - name: Compiling electrostatic4j Java Binding API
          run: ./helper-scripts/ci-cd/compile-e4j.sh
          
        - name: Testing electrostatic4j Java Binding API
          run: ./helper-scripts/ci-cd/test-e4j.sh
